blank_issues_enabled: false
contact_links:
  - name: Bug report - Documentation
    url: https://github.com/MillenniumMachines/millenniummachines.github.io/issues/new?assignees=&labels=Milo&projects=&template=bug-report--milo-docs.md&title=
    about: Suggest an improvement to the documentation on the docs page.
    
  - name: Ask a question
    url: https://discord.gg/ZkRgwg7sB7
    about: Please visit the discord to ask questions!
